---
- hosts: localhost
  become: yes

  tasks:
    - name: Setup path
      set_fact:
        device_path: '/dev/foo/test2'

    - name: Setup fs-type
      set_fact:
        fs_type: 'ext4'
    #
    - name: Setup device name
      set_fact:
        device_name: 'luks-test'

    - name: Setup mount point
      set_fact:
        mount_point: '/opt/test10'

    - name: Setup state variable
      set_fact:
        state: 'absent'

    - name: Setup default mount flag
      set_fact:
        mount_device: true

    - name: Setup luks device
      expect:
        command: cryptsetup -q luksFormat {{ device_path }}
        responses:
          'Enter passphrase for /dev/foo/test2:': "ThisIsSecure"
      when: state == "present"

    - name: Remove luks key
      command: cryptsetup luksRemoveKey /dev/mapper/{{ device_name }}
      when: state == "absent"

    - name: Remove luks volume
      expect:
        command: cryptsetup -q remove {{ device_path }}
        responses:
          'Enter passphrase for {{ device_path}}:': "ThisIsSecure"
      when: state == "absent"

    - name: Open luks device
      expect:
        command: cryptsetup luksOpen {{ device_path }} {{ device_name }}
        responses:
          'Enter passphrase for /dev/foo/test2:': "ThisIsSecure"
      when: state == "present"

    # Install pexpect using pip
    - name: Create fs signature
      filesystem:
        dev: "/dev/mapper/{{ device_name }}"
        fstype: "{{ fs_type }}"
      when: state == "present"

    - name: Mount luks device
      mount:
        src: "/dev/mapper/{{ device_name }}"
        path: "{{ mount_point }}"
        fstype: "{{ fs_type }}"
        state: "{{ state }}"
      when: mount_device and state == "present"
