---
- set_fact:
    pass_response:
      "Enter passphrase for {{ device_path }}:": "ThisIsSecure"

- name: Setup luks device
  expect:
    command: cryptsetup -q luksFormat {{ device_path }}
    responses: "{{ pass_response }}"

- name: Open luks device
  expect:
    command: cryptsetup -q luksOpen {{ device_path }} {{ device_name }}
    responses: "{{ pass_response }}"

- name: Create fs signature
  filesystem:
    dev: "/dev/mapper/{{ device_name }}"
    fstype: "{{ fs_type }}"

- name: Mount luks device
  mount:
    src: "/dev/mapper/{{ device_name }}"
    path: "{{ mount_point }}"
    fstype: "{{ fs_type }}"
    state: "{{ state }}"
