---
- set_fact:
    device_path: '/dev/mapper/{{ lvm_vg }}-{{ lvm_device_name }}'
  when: lvm_vg and device_name

# - name: Save passcode to encrypted file
#   local_action:
#     copy:
#       content: "{{ passcode }}"
#       dest: "../files/pass-default.yml"

- name: Install dependencies as needed
  include_tasks: 'install-commands.yml'
  when: install_dep

# To-Do: fix this as device might have different passcode
- name: Check if device already exists
  stat:
    path: "/dev/mapper/{{ device_name }}"
  register: device_status

- name: Debug stat output
  debug:
    var: device_status

- set_fact:
    dm_path: "/dev/mapper/{{ device_name }}"

- set_fact:
    state: 'absent'
  when: device_status.stat.exists

# tasks file for role
- name: Setup crypt device
  include_tasks: "create-device.yml"
  when: state == "present"

- name: Remove crypt device
  include_tasks: "absent-device.yml"
  when: state == "absent"

- name: Update facts
  setup:
